Quotes Language:		german
Base Header Level:	3
latex input:				basis-mmd-scrartcl|basis-mmd-scrreprt|basis-mmd-scrbook
MyOptions:					draft|final, font=charter|droid|hfold|mathpazo|original|times, fontsize=<groesse>, hypercolor=<color>, hyperdriver=<driver>, notitlepage, oneside, protocol, pagestyle=beides|fuss|fussseite|leer, rules
latex input:				basis-mmd-style
Title:							Dokumenttitel
Date:
Author:							Autorname
MySubtitle:
MyVersion:
MyStrasse:
MyPLZ:
MyOrt:
MyTelefon:
MyHandy:
MyEmail:
MyHomepage:
MyAdresszusatz:
MyTitelzusatz:
MyLogo:
latex input:				basis-mmd-begin-doc

<!-- \maketitle -->

<!-- \tableofcontents -->
<!-- \cleardoublepage -->

# Kapitel 1 [sec:kap1]

Hier sollte richtiger Inhalt stehen.

